{% set name = "odl" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/odlgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: dec092ce1f152707d821146046d4d1441672ad6c22d28dd46e1f77d79c210a38

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools >=65.6

  run:
    - python >=3.7
    - future >=0.16
    - numpy >=1.19
    - scipy >=1.1
    - packaging >=17.0
    - matplotlib-base >=3.4

test:
  requires:
    - nomkl  # [not win]
    - pytest >=5.4
  imports:
    - odl
  commands:
    - python -c "import odl; odl.test()"

about:
  home: https://github.com/odlgroup/odl
  license: MPL-2.0
  license_file: LICENSE
  summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"
  doc_url: https://odlgroup.github.io/odl/
  dev_url: https://github.com/odlgroup/odl

extra:
  recipe-maintainers:
    # Ozan Öktem
    - ozanoktem
    # Justus Sagemüller
    - leftaroundabout
    # Emilien Valat
    - Emvlt
